### ISSUE TITLE
Achievements seem to be bugged at times

### ISSUE THREAD

**Issue by IDGCaptainRussia94** [webmilio/WebmilioCommons-Releases#2]
So here's what I've managed to gather on this:
The first mod I load my mod, it all works fine, things unlock as expected and stay unlocked should I leave the world and come back
But when I exit out and recompile my mod, things don't properly unlock anymore, there's no splash text at the bottom of the screen, but they do unlock in the achievements menu. However, if I leave the world and rejoin they don't stay unlocked, heck anything I had unlocked previously is also locked again.
Even when I deleted the data file and recompiled my mod/reloaded all my mods it doesn't even generate a new data file which, makes no sense to me as well.

This might be some kind of flaw brought over by achievement lib, since I noticed this also happening with Jetshift as well, it's very strange and I'm reporting what I did to recreate it.

**Comment by webmilio** [comment]
Achievements have been removed from tML on Steam.
